import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/intake-invite?token=<uuid>
 *
 * Validates the intake invite token generated by `sendIntakeInvitation`.
 * Marks the lead status as INTAKE_INVITED (idempotent) and redirects
 * the client to the login page with their email pre-filled.
 * The actual portal access is gated by Supabase auth — the setup link
 * in the invitation email already handles authentication.
 */
export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const token = searchParams.get("token");

  if (!token) {
    return NextResponse.redirect(`${origin}/login?error=invalid_invite`);
  }

  const lead = await prisma.lead.findUnique({
    where: { inviteToken: token },
    select: {
      id: true,
      email: true,
      inviteTokenExpiry: true,
      status: true,
    },
  });

  if (!lead) {
    return NextResponse.redirect(`${origin}/login?error=invalid_invite`);
  }

  if (lead.inviteTokenExpiry && lead.inviteTokenExpiry < new Date()) {
    return NextResponse.redirect(`${origin}/login?error=invite_expired`);
  }

  // Mark status idempotently
  if (lead.status !== "INTAKE_INVITED" && lead.status !== "INTAKE_SUBMITTED") {
    await prisma.lead.update({
      where: { id: lead.id },
      data: { status: "INTAKE_INVITED" },
    });
  }

  // Redirect to login with email pre-filled
  const loginUrl = new URL("/login", origin);
  loginUrl.searchParams.set("email", lead.email);
  loginUrl.searchParams.set("message", "account_ready");

  return NextResponse.redirect(loginUrl.toString());
}
